version: "3"
services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/demo?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: tananh3420
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: tananh3420
      MYSQL_DATABASE: demo
      MYSQL_USER: